import dotenv from 'dotenv';

dotenv.config();

export default {
  NODE_ENV: process.env.NODE_ENV,
  PORT: process.env.PORT,
  DATABASE_URL: process.env.DATABASE_URL,
  BCRYPT_SALT_ROUNDS: process.env.BCRYPT_SALT_ROUNDS,
  JWT_ACCESS_SECRET_KEY: process.env.JWT_ACCESS_SECRET_KEY,
  JWT_REFRESH_SECRET_KEY: process.env.JWT_REFRESH_SECRET_KEY,
  JWT_ACCESS_EXP_TIME: process.env.JWT_ACCESS_EXP_TIME,
  JWT_REFRESH_EXP_TIME: process.env.JWT_REFRESH_EXP_TIME,
  FIRST_ADMIN_EMAIL: process.env.FIRST_ADMIN_EMAIL,
  FIRST_ADMIN_PASSWORD: process.env.FIRST_ADMIN_PASSWORD,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_SECRET_KEY: process.env.CLOUDINARY_SECRET_KEY,
  GMAIL_ADDRESS: process.env.GMAIL_ADDRESS,
  GMAIL_APP_PASS: process.env.GMAIL_APP_PASS,
  AAMAR_PAY_INITIATE_URL: process.env.AAMAR_PAY_INITIATE_URL,
  AAMAR_PAY_VERIFY_URL: process.env.AAMAR_PAY_VERIFY_URL,
  AAMAR_PAY_STORE_ID: process.env.AAMAR_PAY_STORE_ID,
  AAMAR_PAY_SIGNATURE_KEY: process.env.AAMAR_PAY_SIGNATURE_KEY,
  AAMAR_PAY_SUCCESS_URL: process.env.AAMAR_PAY_SUCCESS_URL,
  AAMAR_PAY_FAILED_URL: process.env.AAMAR_PAY_FAILED_URL,
  AAMAR_PAY_CANCEL_URL: process.env.AAMAR_PAY_CANCEL_URL,
};
